import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ar';

export const translations = {
  en: {
    appName: "A2M MED",
    logout: "Logout",
    welcome: "Welcome",
    role_admin: "Admin",
    role_supervisor: "Supervisor",
    role_engineer: "Engineer",
    role_technician: "Technician",
    role_nurse: "Nurse",
    role_vendor: "Vendor",
    role_inspector: "Inspector",
    login_title: "Sign in to your account",
    login_subtitle: "Enter your credentials to access the system",
    email_label: "Email Address",
    password_label: "Password",
    btn_login: "Sign In",
    login_error: "Invalid email or password",
    or_continue_as: "Or continue with Demo Persona",
    select_persona: "Select a Persona to Demo:",
    logging_in: "Logging in...",
    nav_dashboard: "Dashboard",
    nav_assets: "Assets & Equipment",
    nav_maintenance: "Maintenance Mgmt",
    nav_inventory: "Inventory & Supply",
    nav_calibration: "Calibration & Quality",
    nav_analysis: "Analysis & Knowledge",
    nav_users: "User Management",
    nav_rfid: "RFID Audit & Tracking",
    nav_inspector: "Compliance Audit",
    op_overview: "Operational Overview",
    total_assets: "Total Assets",
    open_tickets: "Open Tickets",
    inventory_alerts: "Inventory Alerts",
    predictive_risk: "Predictive Risk Analysis",
    dept_map: "Live Department Map",
    unauth_move: "Unauthorized Move",
    kpi_mtbf: "Mean Time Between Failures (MTBF)",
    kpi_mttr: "Mean Time To Repair (MTTR)",
    failure_trend: "Failure Analysis Trend",
    kpi_availability: "Asset Availability",
    alert_boundary: "Boundary Alert",
    alert_boundary_msg: "Asset crossed unauthorized boundary",
    justification_required: "Movement Justification Required",
    enter_reason: "Enter reason for movement...",
    btn_justify: "Submit Justification",
    compliance_reports: "Compliance Reports",
    add_equipment: "Add Equipment",
    tab_list: "Equipment List",
    tab_tracking: "Tracking & Movement Log",
    tab_docs: "Document Archive",
    asset_info: "Asset Info",
    location: "Location",
    status: "Status",
    purchase_date: "Purchase Date",
    risk_score: "Risk Score",
    actions: "Actions",
    asset_details: "Equipment Details",
    manufacturer: "Manufacturer",
    serial_number: "Serial Number",
    warranty_exp: "Warranty Expiry",
    uptime: "Uptime (YTD)",
    mtbf: "MTBF",
    maintenance_history: "Maintenance History",
    live_readings: "Live Readings",
    temperature: "Temperature",
    voltage: "Voltage",
    last_updated: "Last Updated",
    specifications: "Specifications",
    vendor_support: "Vendor Support",
    modal_add_title: "Add New Equipment",
    form_name: "Equipment Name",
    form_model: "Model",
    form_sn: "Asset ID / S/N",
    form_location: "Location",
    form_date: "Purchase Date",
    form_image: "Asset Image",
    btn_save: "Save Asset",
    tab_wo: "Work Orders",
    tab_pm: "Preventive Plans (PM)",
    tab_requests: "Requests",
    tab_ai: "Predictive AI",
    wo_id: "WO ID",
    assigned: "Assigned",
    priority: "Priority",
    type: "Type",
    view_board: "Board View",
    view_list: "List View",
    create_wo: "Create Work Order",
    wo_title: "Work Orders",
    wo_status_open: "Open",
    wo_status_inprogress: "In Progress",
    wo_status_closed: "Closed",
    wo_status_awaiting: "Awaiting Approval",
    wo_status_manager_approved: "Manager Approved",
    wo_status_final_acceptance: "Awaiting Final Acceptance",
    assign: "Assign",
    filter_all: "All",
    assign_technician: "Assign Technician",
    select_tech: "Select Technician / Engineer",
    wo_assigned_msg: "Notification sent to assigned technician.",
    btn_assign_confirm: "Confirm Assignment",
    wo_status_assigned: "Assigned",
    btn_review_approve: "Review & Approve",
    approval_workflow: "Approval Workflow",
    manager_review: "Site Manager Review",
    supervisor_review: "Supervisor Review",
    verify_time_asset: "Verify Time & Asset",
    verify_parts_tech: "Verify Parts & Technical",
    confirm_stock_deduction: "Confirm Stock Deduction",
    btn_approve_sign: "Approve & Sign",
    waiting_manager: "Waiting for Manager",
    waiting_supervisor: "Waiting for Supervisor",
    modal_create_wo: "Dispatch Work Order",
    wo_description: "Fault Description / Task",
    wo_asset: "Select Asset",
    wo_assign_tech: "Assign Technician",
    btn_dispatch: "Dispatch Order",
    tab_stock: "Current Stock",
    tab_logs: "Stock Logs",
    tab_alerts: "Reorder Alerts",
    part_name: "Part Name",
    stock_level: "Stock Level",
    unit_cost: "Unit Cost",
    btn_order: "Order Parts",
    btn_restock: "Restock",
    restock_modal_title: "Restock Inventory",
    restock_qty: "Quantity to Add",
    confirm_large_restock_title: "Large Restock Warning",
    confirm_large_restock_msg: "You are about to add a large quantity ({qty} units) to the inventory. This might be a mistake. Please confirm.",
    current_stock_label: "Current Stock",
    min_level_label: "Min Level",
    restock_btn: "Add to Stock",
    cal_dashboard: "Calibration & Quality Control",
    cal_schedule: "Calibration Schedule",
    cal_certs: "Certificates",
    last_cal: "Last Calibration",
    next_due: "Next Due Date",
    cal_status: "Compliance Status",
    cal_overdue: "Overdue",
    cal_compliant: "Compliant",
    cal_due_soon: "Due Soon",
    btn_update_cal: "Update Calibration",
    update_cal_title: "Record Calibration",
    new_cal_date: "New Calibration Date",
    btn_record: "Record",
    tab_analysis: "Analysis & Reports",
    tab_reports: "Reports",
    tab_kb: "Knowledge Base",
    tab_gen_report: "Report Generator",
    tab_analytics: "Strategic Analytics",
    tab_financial: "Cost & Performance",
    tab_vendor: "Vendor Ratings",
    tab_training: "Training Dashboard",
    tab_budget: "Capital Budget (5-Year)",
    gen_report: "Generate Report",
    report_type: "Report Type",
    cm_report: "Corrective Maintenance (CM)",
    ppm_report: "Preventive Maintenance (PPM)",
    comp_report: "Compliance & Regulatory",
    date_range: "Date Range",
    download_pdf: "Download PDF",
    generated_reports: "Generated Reports",
    pillar_operational: "Operational Efficiency",
    pillar_assets: "Asset Management & Predictive",
    chart_mttr_trend: "MTTR Trend (Monthly)",
    chart_tech_perf: "Technician Performance Analysis",
    chart_downtime_loc: "Downtime by Department",
    chart_asset_status: "Current Asset Status",
    chart_fault_dist: "Fault Distribution by Equipment",
    chart_qc_analysis: "Quality Control Analysis",
    chart_cost_vs_value: "Maintenance Cost vs Purchase Value",
    chart_freq_vs_cost: "Maintenance Frequency vs Cost",
    table_risk_report: "Predictive Risk Report",
    table_financial_report: "Asset Financial Health",
    lbl_avg_mttr: "Avg MTTR",
    lbl_wo_count: "WO Count",
    lbl_user_error: "User Errors",
    lbl_tech_fault: "Technical Faults",
    kb_library: "Document Library",
    kb_ai_search: "AI Smart Search",
    ai_search_title: "Analyze Error Code / Fault",
    ai_search_placeholder: "Enter Error Code (e.g. Err 305) or Fault Description...",
    btn_analyze: "Analyze with AI",
    analyzing: "Analyzing...",
    ai_explanation: "Technical Explanation",
    ai_solution: "Recommended Solution",
    ai_ref_docs: "Referenced Documents",
    tech_dashboard: "Technician Dashboard",
    btn_start_job: "Start Job (Scan NFC)",
    step_verify: "Verification",
    step_diagnosis: "Diagnosis",
    step_inventory: "Inventory & Data",
    step_visual: "Visual Support",
    step_closure: "Closure",
    scan_tag: "Scan Tag",
    match_verified: "Match Verified",
    observed_symptoms: "Observed Symptoms",
    solution_applied: "Repair Actions Taken",
    smart_kb: "Smart Knowledge Base",
    get_suggestions: "Diagnose & Suggest Parts",
    op_hours: "Cumulative Operating Hours",
    spare_parts: "Spare Parts Consumed",
    ar_guide: "Augmented Reality Guide",
    activate_ar: "Activate AR Guide",
    summary: "Summary",
    digital_sig: "Technician Digital Signature",
    close_wo: "Submit for Approval",
    back: "Back",
    next_step: "Next Step",
    todo: "To Do",
    inprogress: "In Progress",
    completed: "Completed",
    tab_new_req: "New Requests",
    tab_scheduled_pm: "Scheduled PMs",
    tab_diagnosis: "Diagnosis Steps",
    tab_parts: "Parts Used",
    tab_checklist: "Checklist",
    tab_finish: "Finish",
    search_parts: "Search Inventory...",
    start_instruction: "Scan NFC to Start Job",
    checklist_progress: "Checklist Progress",
    confirm_close_title: "Submit for Approval",
    confirm_close_msg: "Are you sure you want to submit this repair report? The Work Order will be sent to the Supervisor for final approval.",
    btn_confirm: "Submit Report",
    btn_cancel: "Cancel",
    manuals_detected: "Reference Documents Detected",
    relevant_docs: "Relevant Manuals & Guides",
    continue_work: "Acknowledge & Continue",
    smart_match: "Smart Match",
    acquiring_location: "Acquiring GPS Location...",
    location_verified: "Location Verified",
    geofence_success: "Geofence Check Passed",
    available_guides: "Available Guides",
    ar_overlay: "AI Overlay",
    ar_simulation_msg: "Highlighting internal power supply unit. Verify voltage output at test points marked in blue.",
    nurse_dashboard: "Nurse & Dept. Dashboard",
    tab_overview: "Overview",
    tab_report: "Report Issue",
    tab_verify: "Verify Repairs",
    my_dept: "My Department",
    running: "Running",
    down: "Down",
    stopped: "Stopped",
    maintenance: "Maint.",
    quick_report: "Report",
    report_issue: "Report Issue",
    report_placeholder: "What seems to be the problem? (e.g., Bed remote not working)",
    btn_report: "REPORT FAULT NOW",
    report_sent: "Report Sent!",
    report_desc: "The button triggers an urgent alert to the nearest technician.",
    detected: "Detected",
    reported: "Reported",
    scan_nfc: "Scan Device NFC",
    identifying: "Identifying Device...",
    tap_instruction: "Tap phone to asset tag",
    scan_qr: "Scan Device QR",
    scanning_qr: "Scanning QR...",
    users_title: "System Users",
    add_user: "Add User",
    user_name: "Name",
    user_email: "Email",
    user_phone: "Phone Number",
    user_role: "Role",
    user_dept: "Department",
    user_password: "Password",
    user_sign: "Digital Signature",
    modal_add_user: "Create New Account",
    upload_sign: "Upload Signature",
    btn_create_user: "Create Account",
    pending_verify: "Pending Verification",
    verify_desc: "Confirm repairs for department assets",
    verify_action: "Verify & Sign",
    verify_title: "Confirm Repair Completion",
    confirm_working: "I confirm the device is working properly",
    nurse_sig: "Nurse Signature",
    btn_verify_close: "Verify & Close Order",
    btn_smart_assign: "Smart Auto-Assign",
    floor_plan_3d: "Interactive 3D Floor Plan",
    view_assets_in_zone: "View Assets in Zone",
    rfid_signal: "RFID Live Signal",
    zone_details: "Zone Details",
    select_zone: "Select a Zone",
    tech_rating: "Technician Rating",
    nurse_satisfaction: "Nurse Satisfaction",
    rate_service: "Rate Service Quality",
    tco_analysis: "TCO & Life Cycle Analysis",
    purchase_price: "Purchase Price",
    maint_cost: "Maint. Cost",
    recommendation: "Recommendation",
    replace: "Replace",
    repair: "Repair",
    ftfr: "First-Time Fix Rate",
    rfid_audit: "RFID Inventory Audit",
    rfid_gate_monitor: "Gate Entry/Exit Monitor",
    start_audit: "Start RFID Audit",
    audit_in_progress: "Audit In Progress...",
    expected_assets: "Expected Assets",
    scanned_assets: "Scanned via RFID",
    missing_assets: "Missing / Not Detected",
    gate_event: "Gate Event",
    gate_enter: "ENTERED",
    gate_exit: "EXITED",
    simulate_scan: "Simulate Handheld Reader",
    simulate_gate_pass: "Simulate Gate Passage",
    audit_summary: "Audit Summary",
    zebra_connected: "Zebra RFD8500 Connected",
    zebra_listening: "Listening for Tags...",
    connect_zebra: "Connect Zebra Scanner",
    zebra_instructions: "Ensure device is paired and in HID Mode",
    gate_network_active: "Gate Network Active",
    gate_network_inactive: "Gate Network Offline",
    activate_gates: "Activate Gate Network",
    deactivate_gates: "Stop Monitoring",
    reader_status: "Reader Status",
    reader_online: "Online",
    reader_offline: "Offline",
    gate_ic: "ICU Entrance",
    gate_er: "ER Main Door",
    gate_or: "Surgery Wing",
    gate_lab: "Lab Access",
    unauthorized_movement: "Unauthorized Movement",
    authorized_movement: "Authorized",
    live_gate_feed: "Live Gate Feed",
    cost_ratio: "Cost Ratio",
    maint_freq: "Maint. Frequency",
    asset_health: "Asset Financial Health",
    tab_roles: "Roles & Permissions",
    manage_roles: "Manage System Roles",
    role_name: "Role Name",
    role_desc: "Description",
    create_role: "Create New Role",
    permissions_matrix: "Permissions Matrix",
    res_assets: "Assets",
    res_wo: "Work Orders",
    res_inventory: "Inventory",
    res_reports: "Reports",
    res_users: "Users",
    res_settings: "Settings",
    act_view: "View",
    act_create: "Create",
    act_edit: "Edit",
    act_delete: "Delete",
    smart_point_title: "Smart Maintenance Point",
    smart_point_subtitle: "Instant Diagnostics & Help",
    quick_guide: "Quick User Guide",
    troubleshooting: "Common Troubleshooting",
    is_problem_solved: "Did this solve the problem?",
    btn_solved: "Yes, Issue Resolved",
    btn_not_solved: "No, Report Fault",
    manual_link: "Open Full Manual",
    status_check: "System Check",
    reputation_score: "Reputation & Compliance",
    misuse_index: "Misuse Rate",
    compliant_depts: "Most Compliant Depts",
    high_misuse_depts: "High Misuse Departments",
    asset_reputation: "Device Reputation (Frequent Misuse)",
    lbl_user_error_rate: "نسبة أخطاء المستخدم",
    lbl_technical_rate: "نسبة الأعطال الفنية",
    score_excellent: "ممتاز",
    score_good: "جيد",
    score_poor: "يحتاج تدريب",
    score_critical: "سوء استخدام حرج",
    reputation_desc: "تحليل لأعطال الأجهزة لتحديد مدى التزام الأقسام واحتياجات التدريب.",
    smart_assistant: "المساعد الهندسي الذكي",
    historical_matches: "مطابقات تاريخية",
    avg_repair_time: "متوسط وقت الإصلاح",
    common_parts: "قطع الغيار المتكررة",
    history_insight: "رؤى تاريخية (نفس الموديل)",
    similar_faults: "أعطال مشابهة",
    no_history: "لا توجد بيانات تاريخية لهذا الموديل.",
    vendor_score: "تقييم الموردين",
    reliability_index: "مؤشر الموثوقية",
    support_speed: "سرعة الدعم (MTTR)",
    rec_buy: "موصى به",
    rec_avoid: "تجنب / أعطال كثيرة",
    vendor_leaderboard: "قائمة أفضل الموردين",
    vendor_table: "التحليل التفصيلي للموردين",
    total_units: "إجمالي الوحدات",
    failure_rate: "معدل الفشل",
    training_dashboard: "لوحة تدريب التمريض",
    top_user_errors: "أكثر ٥ أخطاء استخدام",
    training_flyer: "نشرة تدريبية",
    educator_recommendation: "توصية المدرب",
    schedule_session_msg: "تم اكتشاف معدل خطأ مرتفع. يوصى بعقد جلسة تدريب.",
    avoidance_tips: "كيفية التجنب",
    print_flyer: "طباعة النشرة",
    select_dept_training: "اختر القسم لتحليل التدريب",
    error_frequency: "التكرار",
    impact_level: "الأثر",
    flyer_preview: "معاينة النشرة",
    session_needed: "تدريب مطلوب",
    no_major_errors: "لم يتم اكتشاف أخطاء استخدام كبيرة. عمل جيد!",
    btn_gen_image: "توليد صورة (AI)",
    generating_image: "جاري التوليد...",
    gen_image_success: "تم إنشاء الصورة!",
    manuf_date: "تاريخ التصنيع",
    install_date: "تاريخ التركيب",
    lifespan: "العمر الافتراضي",
    years: "سنوات",
    tab_history: "السجل",
    download_manual: "تحميل PDF",
    manual_unavailable: "الكتيب غير متاح",
    doc_type: "نوع المستند",
    file_size: "الحجم",
    asset_timeline: "الجدول الزمني للأصل",
    event: "حدث",
    date: "التاريخ",
    inspector_search_placeholder: "ابحث عن رقم الأصل (AST-1002) أو رقم التحكم...",
    compliance_docs: "الامتثال والشهادات",
    qa_reports: "تقارير الجودة",
    calibration_certs: "شهادات المعايرة",
    view_asset_file: "عرض ملف الأصل",
    search_assets: "البحث في الأصول",
    asset_file: "ملف الأصل",
    risk_level: "مستوى الخطر",
    next_cal_due: "المعايرة القادمة",
    history_log: "سجل العمليات",
    download: "تحميل",
    btn_tech_arrived: "حضور الفني",
    tech_arrived_msg: "تم تسجيل وقت وصول الفني للبلاغ رقم #{id}.",
    active_requests: "الطلبات النشطة",
    no_active_requests: "لا توجد طلبات نشطة حالياً.",
    control_no: "رقم التحكم",
    classification: "التصنيف",
    forecast_5y: "توقعات ميزانية رأس المال (5 سنوات)",
    total_budget_req: "إجمالي الميزانية المطلوبة",
    critical_replacements: "استبدالات حرجة",
    budget_breakdown: "تفاصيل الميزانية حسب السنة",
    replacement_reason: "سبب الاستبدال",
    reason_age: "انتهاء العمر الافتراضي",
    reason_risk: "درجة مخاطرة عالية",
    reason_tco: "تقادم اقتصادي (TCO)",
    estimated_cost: "تكلفة الاستبدال التقديرية",
    replacement_year: "سنة الاستبدال",
    book_value: "القيمة الدفترية الحالية",
    avg_annual_spend: "متوسط الإنفاق السنوي",
    tab_advanced: "Advanced Reports",
    report_mttr_desc: "Monthly MTTR Trend (Hours)",
    report_pm_comp_desc: "PM Compliance Rate (%)",
    report_tech_perf: "Technician Performance Matrix",
    report_dept_cost: "Department Maintenance Cost Analysis",
    compliance_rate: "Compliance Rate",
    reopened_rate: "Re-opened Rate",
    total_wo: "Total WO",
    parts_cost: "Parts Cost",
    labor_cost: "Labor Cost",
    total_cost: "Total Cost",
    monthly_trend: "Monthly Trend",
    total_asset_value: "إجمالي قيمة الأصول",
    total_maint_cost: "إجمالي تكلفة الصيانة",
    financial_health: "الصحة المالية",
    description: "الوصف"
  }
};

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: keyof typeof translations['en']) => string;
  dir: 'ltr' | 'rtl';
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'en' ? 'ar' : 'en'));
  };

  const t = (key: keyof typeof translations['en']): string => {
    return translations[language][key] || key;
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t, dir }}>
      <div dir={dir} className={language === 'ar' ? 'font-arabic' : 'font-sans'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};